### ISSUE TITLE
User Story 2.2

### ISSUE THREAD

**Issue by ezRAez** [EARnagram/reversi#1]
Having trouble assigning the logic of the rules of Reversi.

I've set up functions that grab the row and column, but my diagonal function does not work in the same way.  I first need to set that up so I can read the complete diagonal as a string like the other two, then be able to patch in my div's ids as coordinate numbers. 

Then i'll need to find a way to use those functions to implement this logic: 
![reversi logic](https://cloud.githubusercontent.com/assets/12765592/8584478/b5782a6a-258b-11e5-934a-6c123cb9096b.jpg)

**Comment by ghost** [comment]
Hi Ezra!

Thanks for the image. Good to see you breaking the problem down.

Your problem is that you are trying to implement all of the game logic at once. Break each discrete rule of the game into a "feature" structured as a user story, and implement one after another.

If necessary, resubmit using the correct structure outlined in the [issues protocol](https://github.com/ga-students/WDI_DTLA_4/tree/master/projects/project_issues_protocol). Closed #1.
